### ISSUE TITLE
Starting a new game after an existing one confuses the dwarves

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#25]
Hi Ross,

Running on MacOs - my dwarves went a little nuts. Starting a new game, I allocated a new stockpile zone (and they dutifully moved the starting resources after I removed the default zone), and then asked them to clear some bushes.

As the game started, our friend ```Message type 310 not handled``` immediately appeared, though I could not see any issues (the message re-appears at speeds relative to game speed setting with 0 messages when paused).

The dwarves cleared almost all the bushes, and then went nuts. They **all** started to attempt to do **something** around a random tile slightly away from the starting zone whilst my terminal started throwing ```Cancelling job because: Target pickup item is no longer in target location``` at me. I'm attaching a video to illustrate:

[Confused Dwarves](https://streamable.com/8m7r3)

If you see the dwarf I selected, it seems they are trying to carry things? I counted - and all starting resources are accounted for. No resources were produced in game.

In the meantime I'll see if I can replicate this...

Best,

Alex

**UPDATE 1:** Behaviour can be interrupted temporarily by issuing another command (e.g. Mine or Move Resources), they eventually execute it (takes a long time to get around to it), and then they go back to idolising the same empty tile and the same ```Cancelling job because: Target pickup item is no longer in target location``` message recurs.

**Comment by rossturner** [comment]
Well that's a new one to me! Very interesting, and thanks for the video
that's super helpful.

Where you can see the log messages (just spit out to the terminal for now)
does it tell you which seed was used when starting the game? If so you can
edit seed.txt and replace 0 with that number to use the same seed so the
starting map and everything else *should* be the same, if that still works.

I've managed to free up Sundays for development time at last, so I'll be
putting in some time looking into this then. Hopefully this is the real
cause of the 310 message issue and we can get both fixed.

**Comment by AlexanderEsin** [comment]
> Where you can see the log messages (just spit out to the terminal for now)
does it tell you which seed was used when starting the game? If so you can
edit seed.txt and replace 0 with that number to use the same seed so the
starting map and everything else *should* be the same, if that still works.

Yes I can get the seed, but like the idiot I am I wiped the terminal output to measure the message output rate (for whatever reason; I need better hobbies). I'll try and catch it next time.

...and as I was typing this I immediately broke the game with ```Message type 310```. Will test, and report in the other thread.

**Comment by rossturner** [comment]
Was this a game that was started (from the main menu)  after another game had been played in the same launch of the client? If so there's a huge chance there's some state left over by accident. That's my best guess so far! If not its Bank to the drawing board.

**Comment by AlexanderEsin** [comment]
So ```Message type 310 not handled``` is definitely due to starting a new game from a launch that previously had a game running. Was just typing this out in Issue#20. In that case, I assume that the **Empty tile excitement** is related - trying to move something left over from a previous instance?

**Comment by rossturner** [comment]
Aha! I'd say that's a breakthrough, yes there must be something carried
over between sessions which is causing it. It's not something I test as
much as I clearly should be doing, so that's probably enough for me to
investigate and stop it happening.

Mistake with programming on my part as it's happened before and I thought I
had a solution to stop it happening again in the future. Still figuring
out  the best way to structure everything to reset data between sessions.

On 2 Mar 2018 18:20, "AlexanderEsin" <notifications@github.com> wrote:

So Message type 310 not handled is definitely due to starting a new game
from a launch that previously had a game running. Was just typing this out
in Issue#20. In that case, I assume that the *Empty tile excitement* is
related - trying to move something left over from a previous instance?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking/issues/25#issuecomment-370006758>,
or mute the thread

**Comment by AlexanderEsin** [comment]
Reproducible on Windows. Exactly the same issue: crowding around tile. Trying to move some carry over resource from previous game instance? New error message might be of help, so attaching image.

![gamecarryoverbug](https://user-images.githubusercontent.com/15325436/36919109-1a05aa16-1e54-11e8-9f07-62ce84506a05.png)

Have a good weekend!

Alex

**Comment by rossturner** [comment]
I've put some code in to handle with state between games a lot better, so hopefully(!) this won't come back again. Will be released as pre-alpha 3 on 1st April.
