### ISSUE TITLE
Unable to load the program.  

### ISSUE THREAD

**Issue by ilovecomix** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#26]
Hello, I downloaded the game and I believe I have installed it.   When I try to launch it the game tries to load and  30 seconds later it crashes.   not sure if I installed it incorrectly or if I did something wrong.    I have installed Pre-Alpha 2 on a windows 10 computer.  

Thanks 

-Steven C.

**Comment by rossturner** [comment]
Hi Steven,

Which operating system are you on? Windows /linux/Unix? 32 or 64 bit? Also
what graphics card do you have?

**Comment by rossturner** [comment]
Best to leave a comment rather than editing as I'm not notified. 

If you're on 32-bit windows 10 that won't work as I haven't released a 32 bit build. 

Otherwise are you able to offer any more information on what happens when you launch the game? Installing should just be a case of extracting the zip file anywhere and running `King under the Mountain.exe`. Does the screen go black/ does the main menu appear?

Finally, the best way to investigate any issues is to launch the `.jar` file from the game's directory using the command prompt, by running `java -jar undermount-desktop.jar` but unfortunately this would require you to install Java 8 (or later) to your machine (if it isn't already) from http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html 

Running the jar file from the command line will print any output to the terminal and will say exactly why something isn't working.

**Comment by ilovecomix** [comment]
hello,  I installed java and all the game does is go to black screen and 10 to 15 seconds later I am back to the desktop again no load screen or anything.  

My computer settings are this(https://ilovecomixarchive.box.com/s/xdjp2hlh2e4wp5pn6tuoq32qkpi2q2me).   
& (https://ilovecomixarchive.box.com/s/7jq9o5yecyrcl5n41g1eregmdv060w76)
the .jar readout is this - (https://ilovecomixarchive.box.com/s/qzgjmvcsrwt5zykbjwx1ry7gdtn3qv3p)

I do know this is alpha so I am used to this.   Thanks for trying to figure it out

**Comment by rossturner** [comment]
Ah, thanks, they're both really useful. Surprisingly the crash is coming from the library I'm using before any of my code is reached at all, which is a first. 

From investigating it, looks like this happens when the graphics card is unsupported. You might be using an onboard/built-in to the motherboard graphics card? First best option is to update your graphics card drivers - looks like they could just be old enough that they're not recognised by this version of the API I'm using. Potentially this can also happen if your windows box is running as a virtual machine and isn't sharing the graphics card to it properly (doubt that's the case here).

Second option is I could enable software emulation of open GL so that it doesn't use open GL from the graphics card at all, but I'm doubtful this will work as the shaders and some other effects need features of the GPU to work. This'll mean a small code change so I'll get this done as soon as I'm able and put out an update to try, but the better option is to update your graphics driver and check what graphics card you have.

**Comment by rossturner** [comment]
Also thanks a lot for your patience in trying this out and getting that output by installing Java!

**Comment by ilovecomix** [comment]
I have an all in one Dell computer so yes that is correct on the graphics card.   I did try Intel to see if there was an update available, nope.  Guessing my system is old.  Hope this info helps older computers run the game.   I love city building gamed and I am now a $3 patron supporter so keep up the good work.
 
(https://ilovecomixarchive.box.com/s/8bp9y4g0sbt51vmdk9nz8vp2awrt1ej1)

oh well ill just have to wait......

**Comment by rossturner** [comment]
I think you may need to directly download the latest drivers from https://www.geforce.com/drivers/results/131447 as I'm not 100% sure the intel update will pick them up. That link is for the Geforce 525M graphics card that you apparently have installed as well as the Intel HD Graphics. I could be wrong there though and the intel update *could* find those nvidia drivers.

In the meantime I'll put out an update today and let you know when, to enable software emulation of Open GL, but I'm really not confident that will work as the game does use some advanced graphics techniques despite how simple it looks.

Thank you so much for supporting the game on Patreon!

**Comment by rossturner** [comment]
Right I've uploaded a new build to https://www.patreon.com/posts/17161442 as https://www.patreon.com/file?h=17161442&i=1951511 

Be great if that sorts it for you, but if it does work I'm expecting it to be really slow. Definitely preferable to try and make sure the graphics card is updated properly as it looks like this error is either due to the drivers being out of date or the graphics card just isn't supported, which I won't be able to do anything about unfortunately.

**Comment by ilovecomix** [comment]
downloaded and added to the computer.   here are the results.  still did not work.  (https://ilovecomixarchive.box.com/s/46mp2aau533mbgxnrwv9k0ihbbsy4zxd)

Now I'm trying the graphics update you sent the link for.

**Comment by rossturner** [comment]
I've looked into it further and your Geforce 525M should definitely be supported, so I can only think it's an issue with out of date drivers that the game doesn't know how to communicate with. Any luck after updating them?

**Comment by ilovecomix** [comment]
Well if you know how to update my system to use OpenGL 2.0 or higher that would probably fix the problem.   I have looked and I'm not sure how to update that.  

Also the answer to the graphics update, no it did not allow the game to load

**Comment by ilovecomix** [comment]
oh, another thing this computer had windows 7 on it when I purchased it new so that might be causing some of the problems.  I will be working on the graphics updates and keep you posted.

**Comment by ilovecomix** [comment]
OK, here is what my computer now says.   
(https://ilovecomixarchive.box.com/s/m56m9dv7xab4xlzwl7nhn2c5t120a77g)
(https://ilovecomixarchive.box.com/s/rcilkzhyc0cf9khjv682w59czc0h28s5)

Then I ran the command line and got the same message from last time.   Well, i am confused?     I run steam games all the time and have over 80 of them and some are a few months old?   Never had this kind of problem before.    Guessing it will be fixed over time.    I love DF and games that involve city building so I do not mind troubleshooting this problem.     

-Steven C.

**Comment by rossturner** [comment]
It's a little odd as your computer shows both an nvidia geforce 525M as well as the intel hd graphics 2000, and either should work fine with the game, it has much lower requirements than pretty much any "normal" game released recently on Steam so I'm surprised at this problem (and nobody else has encountered this one yet or at least told me so). It is slightly more uncommon for a game to be using OpenGL than DirectX but still common enough I'd be surprised if it was a big issue for anyone.

I (think) it does require OpenGL 2 as you've come across, but you can see in your own screenshot that your drivers are supporting version 3. Still, as you can see from the console output (image 5) it's picking up only version 1 which is causing the error...

Anyway enough waffling, I've been investigating further while typing this out and it looks like it's a bug in the version of Java that I've bundled with the game (1.8.0_65) which has been confirmed in this issue with LWJGL (the underlying game development library) https://github.com/LWJGL/lwjgl/issues/119 and it looks like it's a problem specifically with just Intel HD 2000 or 3000 graphics cards on windows 10.

...

Further investigation and it looks like it's Intel specifically dropping support for these cards from now on (i.e. in Windows 10) which is no good. There is a workaround someone posted at https://github.com/LWJGL/lwjgl/issues/119#issuecomment-262090230 - fortunately Minecraft uses the same underlying LWJGL library so there's a lot of people experiencing this issue with that game! However I don't think there's any major reason I shouldn't package the older version of Java with the game that works with these graphics cards, so I'll get on that and put a new update out.

**Comment by rossturner** [comment]
Oh also meant to say thanks for your patience with this and sorry you had to be the first person to be hit by it and suffer through! Really appreciate that you like how the game's shaping up and I'm determined to get this working for you!

**Comment by rossturner** [comment]
Right! Fortunately that didn't take long. Bit more confident now I know there's a real underlying issue causing the problem. You can download a new build from https://www.patreon.com/posts/17161442 (pre-alpha 2.2 now) which has a good chance of sorting (or in this case avoiding) the issue - use the included .exe to launch the game and it'll use what's now the Java runtime for version 1.8.25 which *should* be okay.

Also, thanks to the initial difficulty in diagnosing this problem, I've added better logging to the game so it should write to the included file `log.txt` while the game is running and capture any errors rather than needing to launch the game from the command line to see this.

**Comment by ilovecomix** [comment]
Man, I thought this was going to work.  Having the same 10-second black screen then back to the desktop.   Though the OpenGL issue is not coming up when I run from the command prompt.  (https://ilovecomixarchive.box.com/s/indztohhqbrq3es6hmix8g60601mo2ko).   At this point, I guess I'm just going to have to get a new computer soon.    Press onward I am sure this will get figured out, it is really starting to bug me that my system is actually starting to act old.

**Comment by AlexanderEsin** [comment]
Hey ilovecomix,

Just wanted to weigh in quickly...

When you call ```java -jar undermount-desktop.jar``` you're using the java version installed on your system instead of the one Ross bundled with the game. Possibly you've already tried, but make sure you either:

>use the included .exe to launch the game and it'll use what's now the Java runtime for version 1.8.25 

as Ross says, **OR** if you want it to go from the command line, try running:
```jre\bin\java -jar undermount-desktop.jar```
which should explicitly call the bundled distribution.

You can confirm that the two commands call different version of java by running (from the king directory):
```
java -version
jre\bin\java -version
```

Fingers crossed :)

Alex

**Comment by rossturner** [comment]
Thanks for the input Alex! Annoyed and disappointed if this one didn't fix it. When you run the game with the included .exe, what gets written to the log.txt file?

**Comment by ilovecomix** [comment]
well,  nothing the log file is still blank.  I don't think the game actually runs at all.

**Comment by ilovecomix** [comment]
well is that not interesting,   got the game to load from the suggestion AlexanderEsin said to do.   Thank you so much.   Glad I finally got the game to load...    

(https://ilovecomixarchive.box.com/s/246in2nmri0h29eityeihg97c1op7d4a)

I will let you know if I have any issues playing the game.

**Comment by ilovecomix** [comment]
ok game looks great for pre-alpha,   log worked :

INFO: Generating map with seed: -2512678862527639072
INFO: Map generation took 1586ms
INFO: Converting MapGen to game map
INFO: Running river...
INFO: River generation took 138ms
INFO: Total map conversion took 1233ms
INFO: Cancelling job because: Some other item already in target placement tile
INFO: Cancelling job because: Some other item already in target placement tile
INFO: Cancelling job because: Some other item already in target placement tile
INFO: Cancelling job because: Some other item already in target placement tile

**Comment by rossturner** [comment]
Fantastic! Glad we got to the bottom of this one, and thanks for your patience with it
