### ISSUE TITLE
New Game button crashes

### ISSUE THREAD

**Issue by JamesTalon** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#33]
Not sure if there was somewhere I missed something important, however any time I run the game through the exe, it crashes when I select New Game. Can provide detailed specs on the hardware if you need it.

**Comment by rossturner** [comment]
Oh dear, yes system specs would help, primarily CPU, graphics card, amount of memory and operating system. 

After the crash what is the contents of the log.txt file?

**Comment by JamesTalon** [comment]
The log.txt file doesn't have much, but this what it shows

INFO: Generating map with seed: 2806670336399764970
INFO: Map generation took 1184ms
INFO: Converting MapGen to game map
INFO: Running river...
INFO: River generation took 133ms
INFO: Total map conversion took 920ms

CPU: i7 4820K
GPU: AMD Radeom R9 270x
RAM: 32GB
OS: Win 10

**Comment by rossturner** [comment]
Hmm, I must be missing something when catching errors to log them, that's what I'd expect to see in the log but then followed with a stack trace of what caused the crash. Assuming you're on win 10 64 bit that system spec is well beyond what should be needed. 

Okay just investigated this and it turns out I won't log an error if it's thrown at the point of starting a new game which is a big hole. I'm going to add that in and release a new version with better logging in, if you could then try that we should capture the exception and be able to see why it's not working (hopefully).

Apologies it's not working for you!

**Comment by JamesTalon** [comment]
Yea it is 64 bit, sorry about that!

**Comment by rossturner** [comment]
No worries :) I assumed it would be but best to make sure.

Right I've now updated https://www.patreon.com/posts/17761422 with a new windows version which should log the error you're getting. It won't fix the problem yet, but this log will let me figure out what's going wrong where.

**Comment by JamesTalon** [comment]
I downloaded it, and now it works perfectly fine. Get in to the game and see the little guys start roaming around. Sadly remoting my desktop doesn't make for a good way to play beyond that

**Comment by rossturner** [comment]
Hah that's really weird but good news I guess. I did put up a 3.1 build earlier and replaced it with what should have been the original 3.0 build, but perhaps I introduced a bug doing that which this has fixed. Either way glad it's working for you! Hopefully you can physically get to your desktop to try it out properly soon :)
